name: Create S3 Bucket

on:
  workflow_dispatch:  # Allows manual trigger from GitHub UI

jobs:
  create-s3-bucket:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Create S3 Bucket
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          # Use a unique bucket name (you can customize the prefix)
          BUCKET_NAME="gh-actions-bucket-${{ github.run_id }}"

          echo "Creating S3 bucket: $BUCKET_NAME in region $AWS_REGION"
